#!/usr/bin/env bash
# Displays information about subdomains

if [ $# -eq 1 ]; then
    queries=("www.$1" "lb-01.$1" "web-01.$1" "web-02.$1")

    for query in "${queries[@]}"; do
        dig_result=$(dig +short "$query")

        if [ -n "$dig_result" ]; then
            subdomain=$(echo "$query" | cut -d'.' -f1)
            server=$(echo "$query" | cut -d'.' -f2-)

            echo "The subdomain $query has IP address: $dig_result"
        else
            echo "The subdomain $query does not have a valid IP address."
        fi
    done
else
    echo "Usage: $0 <domain>"
fi
